on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        format: tty

  dash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck to check against dash shells
      uses: ludeeus/action-shellcheck@master
      with:
        format: tty
      env:
        SHELLCHECK_OPTS: --shell dash
